### ISSUE TITLE
Feedback on Installation Instructions

### ISSUE THREAD

**Issue by Kilowog01** [valentyn-l/GTAIV.EFLC.Various.Fixes#10]
I am writing to express my concerns regarding the installation instructions for the mod I recently attempted to install a few times with no success. I've provided some background information to help you understand my situation better:

- My PC is running smoothly and stable. 
- Windows 11, Ryzen 3700x, 32GB DDR4, GTX 1080 8GB.
- I recently formatted my PC, and very few applications have been installed besides steam.
- My GTA IV CE version is 1.2.0.59, and it is an original Steam copy without downgrades.

- The specific mods I am attempting to install(exactly in this order) are FusionFix (compatible with v1.2.0.30 and above), IVCERadioRestorer (compatible with the CE version), a Brazilian Portuguese translation and VariousFixes.

The issue arises when I attempt to install VariousFixes. The game starts crashing at random points. I've tried my best to follow the installation instructions but have encountered some confusion and potential issues that I believe need attention and clarification.

1. **Number of Installation Options:**
Are three installation options really necessary? It seems confusing, especially when the "Automatic" option is not truly automatic but rather a manual process with fewer steps. The naming is misleading and could be clarified. We basically have a trilogy of manual installations.

2. **Fusion Fix Overload System:**
The reference to "Fusion Fix Overload System" is unclear, and I couldn't find information on it even through online searches. As we progress through the steps, it becomes apparent that it is not a standalone software that needs installation. However, the initial mention in the first line is disconnected and might cause confusion.

3. **Manual Installation:**
It would be beneficial to outline the advantages and disadvantages of the manual method. Who is this method ideal for, and for which game versions. Currently, this information is lacking.

4. **Auto-Install Option:**
The instruction to copy "update.img" to the "update" folder assumes the existence of the "update" folder, which may not be present if FusionFix is not installed. This should be explicitly mentioned. The statement about not working with EFLC files is confusing and may need clarification.

5. **Through Fusion Overloader:**
The purpose and advantages of using Fusion Overloader are not clear. Users would benefit from information on who this method is suitable for and its compatibility with different game versions.

In conclusion, enhancing the clarity of these instructions will undoubtedly improve the user experience and reduce potential errors. Users should have a clear understanding of each installation option, its requirements, potential conflicts, compatibility issues, and when it is most appropriate. As a user, I am willing to invest time in the installation process, provided the instructions are well-structured and easy to follow. However, the frustration and time wasted trying to decipher unclear steps and troubleshooting issues can be considerable.

Best regards,
Kilowog01

**Comment by Attramet** [comment]
1. Is this a bad thing? I even separated these installations so that the player does not install all of them just to use only one, and there is still something not right.
About Auto-Installation, how it should be named then? I specified in readme file that this is an "update.img method", if I name this installation as "update.img installation" player definetely wouldn't understand what is this.
Installation is not truly automatic? it's basically drag and drop, or do you mean EFLC? if yes then well, this is something I can't do anything about, that's the way update.img system works.

2. You didn’t search well then, and this installation is made for those who uses Fusion Fix, if the player doesn’t know what it is, then he shouldn’t even touch it.

3. This installation method is made for people who either do not trust auto-installers, or have reasons not to install some files, in any case, this is at the discretion of the player himself, nowhere is said about any advantages or disadvantages of this installation, so whats the point of clarifying something if the contents are no different?

4. What? It doesn't say to move "update.img" to "update" folder, it says to move the "update" folder to the game folder and along with it pc and common folders. Have you installed 1.7 version? because I have no clue where you have read this.
Statement about not working with EFLC files can be clarified, sure, the point that the files do not work with EFLC, because EFLC files is in priority and do not allow the modded ones to be loaded, but what this information give the player? just extra text and nothing more that he can do about it.

5. In readme, in section with Auto-Installation, there is a transition to installation via Fusion Overloader, which says that installing the mod using Fusion Fix will allow you to install the files without even replacing the original ones, how's this not an advantage of using that installation?
The only thing I missed was the opportunity to also automatically install fixes for EFLC, but it's just ridiculous to find fault in such moments.

Last part of the text was generated by AI? Relax max, it's not a parade or anything, this is just a mod and not some official thing from developers.
No one complained about misunderstandings with installations, people install and play with this mod. About random crashes, I understand, I’ll try to see what this might be connected with, but so far you are the first to write about it, so it takes time to find out the reasons why this happen.

**Comment by Kilowog01** [comment]
Okay, this is a bit scary and embarrassing...

There's a good reason I was the first to complain. My difficulty in interpreting the readme wasn't caused by the version, stupidity or language barrier. It was simply heat, the temperatures in Rio are insanely hot right now. You can check the news, a thousand people passed out and one died at a Taylor Swift concert yesterday. Some soccer fields registered 158°F. Remember that whole moving "update.img" thing? It's not written anywhere, I'm pretty sure that was a hallucination.

I tried to install these mods about six times yesterday, the random crashes were probably a result of my fried brain not being able to install things correctly. I'll try VariousFixes again using the Overload method, if I get crashes I'll just play without it since my game is working fine without it.

Also I learned from many horrible experiences that programmers tend to be allergic to real user experience. So i try to mask criticism with flattery, detail and formality so i don't get "skill issue git gut lol" or worse in response.

Since I already opened the issue, here are some things that could be better rewritten:
>To install it, just drop the "update" folder into the game folder, then check pc and common folders and drop all files from there with replacement, or just drop these two folders with file replacement.

That was a weird way of saying "Drop and replace all content of this folder into the GTAIV directory."
>This method does not work with EFLC files, so fixes for EFLC you can install only manually

If the intention is to make the EFLC user skip this method and go straight to the manual, this could be said a bit more clearly. Otherwise, it can lead the user to mix two installation methods, which is what I did.

2. I have FusionFix installed and I don't know what "Fusion Fix Overload System" is, i checked and is not mentioned in FusionFix's git. If it's not important, perhaps a "Use this method if you have FusionFix installed" would fit better. But obviously none of this is a big deal. Anyway, I'm sorry for the confusion and for wasting your time.

With love,
An overheated human
